## Ансамбли деревьев

In [40]:
import pandas as pd
import optuna
import numpy as np

from sklearn.ensemble import BaggingRegressor, GradientBoostingRegressor, StackingRegressor
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import ElasticNet

### Задача регрессии

In [9]:
regression = pd.read_csv("../data/diamonds_filtered.csv")

In [11]:
y_regression = regression['price']
x_regression = regression.drop('price', axis=1)

In [21]:
results = []
def metrics(model, model_name, r2):
    x_train, x_test, y_train, y_test = train_test_split(
    x_regression, y_regression, test_size=0.2, random_state=81)

    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    metrics = {
        'Model': model_name,
        'MAE': round(mean_absolute_error(y_test, y_pred), 4),
        'RMSE': round(np.sqrt(mean_squared_error(y_test, y_pred)), 4),
        'MAPE': round(mean_absolute_percentage_error(y_test, y_pred), 4),
        'R2 (Test)': round(model.score(x_test, y_test), 5),
        'R2 (CV)': round(r2, 5) 
    }

    results.append(metrics)

### BaggingRegressor

In [ ]:
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 5, 15),
        'max_samples': trial.suggest_float('max_samples', 0.5, 0.8),
        'max_features': trial.suggest_float('max_features', 0.5, 1.0),
        'bootstrap': True,
        'bootstrap_features': False,
        'n_jobs': -1,
        'random_state': 81,
        'verbose': 0
    }

    model = BaggingRegressor(**params)

    kf = KFold(n_splits=5, shuffle=True, random_state=81)
    score = cross_val_score(
        estimator=model, 
        X=x_regression, 
        y=y_regression, 
        scoring='r2', 
        cv=kf, 
        n_jobs=-1
    ).mean()

    return score

In [23]:
study = optuna.create_study(direction='maximize')
study.optimize(func=objective, n_trials=50, n_jobs=-1)

[I 2026-04-11 10:27:16,520] A new study created in memory with name: no-name-4742e1fb-4ac5-41be-abcc-25179bd20f3e
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:18,468] Trial 1 finished with value: 0.5999288037795779 and parameters: {'n_estimators': 5, 'max_samples': 0.7897156690761369, 'max_features': 0.5630389213000655}. Best is trial 1 with value: 0.5999288037795779.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:18,755] Trial 2 finished with value: 0.6019928833632384 and parameters: {'n_estimators': 5, 'max_samples': 0.7173636296977499, 'max_features': 0.6623225173502558}. Best is trial 2 with value: 0.6019928833632384.
[I 2026-04-11 10:27:18,786] Trial 0 finished with value: 0.9803677842287029 and parameters: {'n_estimators': 8, 'max_samples': 0.5436713026024959, 'max_features': 0.9193853936785663}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:18,962] Trial 3 finished with value: 0.8297186264788241 and parameters: {'n_estimators': 6, 'max_samples': 0.5963533962562365, 'max_features': 0.7464572630550601}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:19,354] Trial 4 finished with value: 0.8492241969909509 and parameters: {'n_estimators': 12, 'max_samples': 0.7844157281229652, 'max_features': 0.5879478402525427}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:19,734] Trial 6 finished with value: 0.8860819122061006 and parameters: {'n_estimators': 11, 'max_samples': 0.5363921304900557, 'max_features': 0.7828256030161211}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:19,768] Trial 8 finished with value: 0.8327924630147635 and parameters: {'n_estimators': 6, 'max_samples': 0.7110876535336798, 'max_features': 0.7209903283117638}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:20,024] Trial 5 finished with value: 0.8152902972359058 and parameters: {'n_estimators': 8, 'max_samples': 0.7427655291864648, 'max_features': 0.6648346251562394}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:20,389] Trial 9 finished with value: 0.9803217192320245 and parameters: {'n_estimators': 15, 'max_samples': 0.5984685327696019, 'max_features': 0.8891421596609375}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:20,503] Trial 7 finished with value: 0.8490414508882125 and parameters: {'n_estimators': 12, 'max_samples': 0.6955051562446589, 'max_features': 0.5890703861260653}. Best is trial 0 with value: 0.9803677842287029.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:1315: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
[I 2026-04-11 10:27:20,686] Trial 10 finished with value: 0.896189516980329 and parameters: {'n_estimators': 8, 'max_samples': 0.565637008601712, 'max_features': 0.8376098266735761}. Best is trial 0 with value: 0.9803677842287029.

In [ ]:
print(f"Best params: {study.best_params}")
print(f"Best R^2: {study.best_value}")

metrics(BaggingRegressor(**study.best_params), 'BaggingRegressor', study.best_value)

Best params: {'n_estimators': 10, 'max_samples': 0.5676322199165681, 'max_features': 0.9467792663403839}
Best R^2: 0.9806168369014105

###  GradientBoostingRegressor

In [33]:
def objective(trial):
    params = {
        'loss': trial.suggest_categorical('loss', ['squared_error', 'absolute_error', 'huber', 'quantile']),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.5),
        'n_estimators': trial.suggest_int('n_estimators', 5, 500),
        'criterion': trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error']),
        'min_samples_split': trial.suggest_int('min_samples_split', 5, 30),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 5, 20),
        'max_depth': trial.suggest_int('max_depth', 2, 10),
        'min_impurity_decrease': trial.suggest_float('min_impurity_decrease', 0.0, 0.1),
        'random_state': 81,
        'ccp_alpha': trial.suggest_float('ccp_alpha', 0.0, 0.01)
    }

    model = GradientBoostingRegressor(**params)

    kf = KFold(n_splits=5, shuffle=True, random_state=81)
    score = cross_val_score(
        estimator=model, 
        X=x_regression, 
        y=y_regression, 
        scoring='r2', 
        cv=kf, 
        n_jobs=-1
    ).mean()

    return score

In [34]:
study = optuna.create_study(direction='maximize')
study.optimize(func=objective, n_trials=50)

[I 2026-04-11 10:53:15,352] A new study created in memory with name: no-name-3cee7410-64c5-46b0-80c0-18845379e2db

[I 2026-04-11 10:53:17,853] Trial 0 finished with value: 0.9814513873612001 and parameters: {'loss': 'squared_error', 'learning_rate': 0.468168629191333, 'n_estimators': 34, 'criterion': 'friedman_mse', 'min_samples_split': 10, 'min_samples_leaf': 11, 'max_depth': 7, 'min_impurity_decrease': 0.014582579336681901, 'ccp_alpha': 0.009170157580667205}. Best is trial 0 with value: 0.9814513873612001.
[I 2026-04-11 10:53:41,926] Trial 1 finished with value: 0.9449646336841724 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.32635870597652417, 'n_estimators': 415, 'criterion': 'friedman_mse', 'min_samples_split': 26, 'min_samples_leaf': 5, 'max_depth': 10, 'min_impurity_decrease': 0.0799786427899379, 'ccp_alpha': 0.006250985814889285}. Best is trial 0 with value: 0.9814513873612001.
[I 2026-04-11 10:53:49,034] Trial 2 finished with value: 0.9819994605424771 and parameters: {'loss': 'squared_error', 'learning_rate': 0.18889195643851645, 'n_estimators': 117, 'criterion': 'friedman_mse', 'min_samples_split': 21, 'min_samples_leaf': 7, 'max_depth': 10, 'min_impurity_decrease': 0.07305557803164182, 'ccp_alpha': 0.0056968415050123065}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:53:57,737] Trial 3 finished with value: 0.9814582590491338 and parameters: {'loss': 'squared_error', 'learning_rate': 0.42392157289207644, 'n_estimators': 496, 'criterion': 'squared_error', 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_depth': 3, 'min_impurity_decrease': 0.0017397763226809305, 'ccp_alpha': 0.007437806706660864}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:09,762] Trial 4 finished with value: 0.9074329389953529 and parameters: {'loss': 'quantile', 'learning_rate': 0.48187992424009435, 'n_estimators': 372, 'criterion': 'friedman_mse', 'min_samples_split': 17, 'min_samples_leaf': 11, 'max_depth': 5, 'min_impurity_decrease': 0.006031483938171722, 'ccp_alpha': 0.00046769600446422313}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:15,847] Trial 5 finished with value: 0.9399640713468143 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.06586311845436568, 'n_estimators': 235, 'criterion': 'friedman_mse', 'min_samples_split': 24, 'min_samples_leaf': 9, 'max_depth': 4, 'min_impurity_decrease': 0.04631228912039283, 'ccp_alpha': 0.00824903489529332}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:28,128] Trial 6 finished with value: 0.9783755162816252 and parameters: {'loss': 'huber', 'learning_rate': 0.014503978648106979, 'n_estimators': 426, 'criterion': 'squared_error', 'min_samples_split': 8, 'min_samples_leaf': 14, 'max_depth': 4, 'min_impurity_decrease': 0.03418972077280633, 'ccp_alpha': 0.0012002596212269045}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:34,186] Trial 7 finished with value: 0.8760631911874921 and parameters: {'loss': 'quantile', 'learning_rate': 0.33064617772200683, 'n_estimators': 170, 'criterion': 'friedman_mse', 'min_samples_split': 27, 'min_samples_leaf': 18, 'max_depth': 6, 'min_impurity_decrease': 0.03727700290654382, 'ccp_alpha': 0.0023714621962075766}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:45,827] Trial 8 finished with value: 0.9549131310997412 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.052508306962531066, 'n_estimators': 282, 'criterion': 'friedman_mse', 'min_samples_split': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'min_impurity_decrease': 0.09240208658009645, 'ccp_alpha': 0.004927723478565598}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:48,869] Trial 9 finished with value: 0.972635662462376 and parameters: {'loss': 'huber', 'learning_rate': 0.28536498498524837, 'n_estimators': 165, 'criterion': 'squared_error', 'min_samples_split': 29, 'min_samples_leaf': 14, 'max_depth': 2, 'min_impurity_decrease': 0.09344325461672541, 'ccp_alpha': 0.008328517167227361}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:49,559] Trial 10 finished with value: 0.9572247884248837 and parameters: {'loss': 'squared_error', 'learning_rate': 0.15471055245780704, 'n_estimators': 11, 'criterion': 'squared_error', 'min_samples_split': 22, 'min_samples_leaf': 18, 'max_depth': 10, 'min_impurity_decrease': 0.06467389121853562, 'ccp_alpha': 0.004458950925254529}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:54:55,541] Trial 11 finished with value: 0.9763500736132432 and parameters: {'loss': 'squared_error', 'learning_rate': 0.19208398631447335, 'n_estimators': 492, 'criterion': 'squared_error', 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'min_impurity_decrease': 0.06278089160371085, 'ccp_alpha': 0.006547516634844408}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:55:01,191] Trial 12 finished with value: 0.9801618151177355 and parameters: {'loss': 'squared_error', 'learning_rate': 0.39904824020330115, 'n_estimators': 125, 'criterion': 'squared_error', 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_depth': 8, 'min_impurity_decrease': 0.018709212639330904, 'ccp_alpha': 0.006609398907815982}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:55:17,087] Trial 13 finished with value: 0.9812540675882906 and parameters: {'loss': 'squared_error', 'learning_rate': 0.19556809318576637, 'n_estimators': 324, 'criterion': 'squared_error', 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'min_impurity_decrease': 0.06668642367247685, 'ccp_alpha': 0.003183430938413382}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:55:19,011] Trial 14 finished with value: 0.981269573382259 and parameters: {'loss': 'squared_error', 'learning_rate': 0.40567673597095694, 'n_estimators': 102, 'criterion': 'friedman_mse', 'min_samples_split': 21, 'min_samples_leaf': 5, 'max_depth': 3, 'min_impurity_decrease': 0.08166094705487678, 'ccp_alpha': 0.007446729469827727}. Best is trial 2 with value: 0.9819994605424771.
[I 2026-04-11 10:55:25,385] Trial 15 finished with value: 0.9831935784491254 and parameters: {'loss': 'squared_error', 'learning_rate': 0.1302825974929251, 'n_estimators': 222, 'criterion': 'squared_error', 'min_samples_split': 20, 'min_samples_leaf': 11, 'max_depth': 5, 'min_impurity_decrease': 0.0005146812457419807, 'ccp_alpha': 0.009952451983804421}. Best is trial 15 with value: 0.9831935784491254.
[I 2026-04-11 10:55:33,044] Trial 16 finished with value: 0.9831357519036128 and parameters: {'loss': 'squared_error', 'learning_rate': 0.11541539262766713, 'n_estimators': 226, 'criterion': 'friedman_mse', 'min_samples_split': 20, 'min_samples_leaf': 12, 'max_depth': 6, 'min_impurity_decrease': 0.0505640207299694, 'ccp_alpha': 0.003272772540427341}. Best is trial 15 with value: 0.9831935784491254.
[I 2026-04-11 10:55:42,840] Trial 17 finished with value: 0.9834477224790735 and parameters: {'loss': 'huber', 'learning_rate': 0.12065526360102874, 'n_estimators': 234, 'criterion': 'squared_error', 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_depth': 6, 'min_impurity_decrease': 0.05252079867076734, 'ccp_alpha': 0.003702099330601164}. Best is trial 17 with value: 0.9834477224790735.
[I 2026-04-11 10:55:53,060] Trial 18 finished with value: 0.9833669021617822 and parameters: {'loss': 'huber', 'learning_rate': 0.1145517065901564, 'n_estimators': 286, 'criterion': 'squared_error', 'min_samples_split': 15, 'min_samples_leaf': 16, 'max_depth': 5, 'min_impurity_decrease': 0.02718267963001734, 'ccp_alpha': 0.009859448911136005}. Best is trial 17 with value: 0.9834477224790735.
[I 2026-04-11 10:56:07,327] Trial 19 finished with value: 0.9827393464533956 and parameters: {'loss': 'huber', 'learning_rate': 0.24239907997522744, 'n_estimators': 299, 'criterion': 'squared_error', 'min_samples_split': 15, 'min_samples_leaf': 20, 'max_depth': 7, 'min_impurity_decrease': 0.027458146683139367, 'ccp_alpha': 0.003495573219274127}. Best is trial 17 with value: 0.9834477224790735.
[I 2026-04-11 10:56:19,577] Trial 20 finished with value: 0.9833784556356173 and parameters: {'loss': 'huber', 'learning_rate': 0.09456475559229154, 'n_estimators': 344, 'criterion': 'squared_error', 'min_samples_split': 18, 'min_samples_leaf': 16, 'max_depth': 5, 'min_impurity_decrease': 0.04989259779700699, 'ccp_alpha': 0.0019188273851634945}. Best is trial 17 with value: 0.9834477224790735.
[I 2026-04-11 10:56:31,988] Trial 21 finished with value: 0.9835381256838355 and parameters: {'loss': 'huber', 'learning_rate': 0.0778582575976445, 'n_estimators': 350, 'criterion': 'squared_error', 'min_samples_split': 17, 'min_samples_leaf': 16, 'max_depth': 5, 'min_impurity_decrease': 0.05064788987663172, 'ccp_alpha': 0.0015913377227345594}. Best is trial 21 with value: 0.9835381256838355.
[I 2026-04-11 10:56:46,893] Trial 22 finished with value: 0.9835734675149064 and parameters: {'loss': 'huber', 'learning_rate': 0.06082877912622872, 'n_estimators': 357, 'criterion': 'squared_error', 'min_samples_split': 19, 'min_samples_leaf': 16, 'max_depth': 6, 'min_impurity_decrease': 0.05278044254619846, 'ccp_alpha': 0.00172006845812308}. Best is trial 22 with value: 0.9835734675149064.
[I 2026-04-11 10:57:09,596] Trial 23 finished with value: 0.983610168486439 and parameters: {'loss': 'huber', 'learning_rate': 0.016919915733007877, 'n_estimators': 385, 'criterion': 'squared_error', 'min_samples_split': 24, 'min_samples_leaf': 15, 'max_depth': 8, 'min_impurity_decrease': 0.05653968695501819, 'ccp_alpha': 3.281367944692475e-05}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:57:33,916] Trial 24 finished with value: 0.983442127944911 and parameters: {'loss': 'huber', 'learning_rate': 0.013803848797822121, 'n_estimators': 408, 'criterion': 'squared_error', 'min_samples_split': 23, 'min_samples_leaf': 18, 'max_depth': 8, 'min_impurity_decrease': 0.05907566989601964, 'ccp_alpha': 0.00042635860154561773}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:57:53,858] Trial 25 finished with value: 0.9834517306506608 and parameters: {'loss': 'huber', 'learning_rate': 0.057593560642131225, 'n_estimators': 362, 'criterion': 'squared_error', 'min_samples_split': 24, 'min_samples_leaf': 17, 'max_depth': 8, 'min_impurity_decrease': 0.042736011036994655, 'ccp_alpha': 0.0015380626846947076}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:58:25,403] Trial 26 finished with value: 0.9828503437150109 and parameters: {'loss': 'huber', 'learning_rate': 0.010053486577827396, 'n_estimators': 441, 'criterion': 'squared_error', 'min_samples_split': 26, 'min_samples_leaf': 20, 'max_depth': 9, 'min_impurity_decrease': 0.05634309243948646, 'ccp_alpha': 0.0009167665826610934}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:58:43,833] Trial 27 finished with value: 0.9834087604195588 and parameters: {'loss': 'huber', 'learning_rate': 0.06912146728002468, 'n_estimators': 380, 'criterion': 'squared_error', 'min_samples_split': 30, 'min_samples_leaf': 14, 'max_depth': 7, 'min_impurity_decrease': 0.07067266535175043, 'ccp_alpha': 0.0024037233226839325}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:58:47,452] Trial 28 finished with value: -1.522205167843996 and parameters: {'loss': 'quantile', 'learning_rate': 0.16691835149418716, 'n_estimators': 460, 'criterion': 'squared_error', 'min_samples_split': 16, 'min_samples_leaf': 13, 'max_depth': 4, 'min_impurity_decrease': 0.03646309426093527, 'ccp_alpha': 0.00037231062641045854}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:59:03,271] Trial 29 finished with value: 0.9826293147792275 and parameters: {'loss': 'huber', 'learning_rate': 0.23583044295186512, 'n_estimators': 332, 'criterion': 'squared_error', 'min_samples_split': 13, 'min_samples_leaf': 16, 'max_depth': 7, 'min_impurity_decrease': 0.043061339193540334, 'ccp_alpha': 1.4265560485693732e-05}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:59:19,519] Trial 30 finished with value: 0.983601198507634 and parameters: {'loss': 'huber', 'learning_rate': 0.044510719766772705, 'n_estimators': 389, 'criterion': 'squared_error', 'min_samples_split': 9, 'min_samples_leaf': 19, 'max_depth': 6, 'min_impurity_decrease': 0.0774240502990938, 'ccp_alpha': 0.002631636333546466}. Best is trial 23 with value: 0.983610168486439.
[I 2026-04-11 10:59:36,168] Trial 31 finished with value: 0.9836361377803039 and parameters: {'loss': 'huber', 'learning_rate': 0.04116143401811084, 'n_estimators': 399, 'criterion': 'squared_error', 'min_samples_split': 9, 'min_samples_leaf': 19, 'max_depth': 6, 'min_impurity_decrease': 0.08197451165795597, 'ccp_alpha': 0.0024345198384354057}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 10:59:52,726] Trial 32 finished with value: 0.9836120687547913 and parameters: {'loss': 'huber', 'learning_rate': 0.03521307626624077, 'n_estimators': 396, 'criterion': 'squared_error', 'min_samples_split': 8, 'min_samples_leaf': 19, 'max_depth': 6, 'min_impurity_decrease': 0.08289597471445612, 'ccp_alpha': 0.0023143377828091813}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:00:09,823] Trial 33 finished with value: 0.9834265230528217 and parameters: {'loss': 'huber', 'learning_rate': 0.021520264331035932, 'n_estimators': 408, 'criterion': 'squared_error', 'min_samples_split': 9, 'min_samples_leaf': 19, 'max_depth': 6, 'min_impurity_decrease': 0.08375400339624468, 'ccp_alpha': 0.0026311730609013158}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:00:13,784] Trial 34 finished with value: 0.6962322781662997 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.039011435450476535, 'n_estimators': 393, 'criterion': 'squared_error', 'min_samples_split': 8, 'min_samples_leaf': 19, 'max_depth': 8, 'min_impurity_decrease': 0.09830007169406303, 'ccp_alpha': 0.004272990377284}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:00:41,253] Trial 35 finished with value: 0.9829946572032375 and parameters: {'loss': 'huber', 'learning_rate': 0.0796745074114057, 'n_estimators': 450, 'criterion': 'squared_error', 'min_samples_split': 5, 'min_samples_leaf': 19, 'max_depth': 9, 'min_impurity_decrease': 0.07515245920708345, 'ccp_alpha': 0.005539484544022107}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:00:43,727] Trial 36 finished with value: -2.0949187615476723 and parameters: {'loss': 'quantile', 'learning_rate': 0.038260254932606125, 'n_estimators': 315, 'criterion': 'squared_error', 'min_samples_split': 10, 'min_samples_leaf': 20, 'max_depth': 6, 'min_impurity_decrease': 0.07576815108901681, 'ccp_alpha': 0.002727160264829688}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:01:06,398] Trial 37 finished with value: 0.9833961129012735 and parameters: {'loss': 'huber', 'learning_rate': 0.09830189479078343, 'n_estimators': 476, 'criterion': 'squared_error', 'min_samples_split': 7, 'min_samples_leaf': 17, 'max_depth': 7, 'min_impurity_decrease': 0.08816962088836004, 'ccp_alpha': 0.004114538604816008}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:01:17,192] Trial 38 finished with value: 0.9745808111962576 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.14867463143658302, 'n_estimators': 417, 'criterion': 'friedman_mse', 'min_samples_split': 11, 'min_samples_leaf': 17, 'max_depth': 4, 'min_impurity_decrease': 0.08600788794197087, 'ccp_alpha': 0.0009763684628260705}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:01:35,995] Trial 39 finished with value: 0.9835402859009609 and parameters: {'loss': 'huber', 'learning_rate': 0.04096573401610707, 'n_estimators': 387, 'criterion': 'squared_error', 'min_samples_split': 7, 'min_samples_leaf': 19, 'max_depth': 7, 'min_impurity_decrease': 0.07746239878986724, 'ccp_alpha': 0.0021590276569196177}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:01:53,661] Trial 40 finished with value: 0.9819917824749206 and parameters: {'loss': 'huber', 'learning_rate': 0.34606426466670315, 'n_estimators': 434, 'criterion': 'squared_error', 'min_samples_split': 10, 'min_samples_leaf': 18, 'max_depth': 6, 'min_impurity_decrease': 0.09097861206080293, 'ccp_alpha': 0.0028140030343717076}. Best is trial 31 with value: 0.9836361377803039.
[I 2026-04-11 11:02:08,653] Trial 41 finished with value: 0.9836454007488242 and parameters: {'loss': 'huber', 'learning_rate': 0.04821424611685163, 'n_estimators': 358, 'criterion': 'squared_error', 'min_samples_split': 6, 'min_samples_leaf': 15, 'max_depth': 6, 'min_impurity_decrease': 0.09893768464041772, 'ccp_alpha': 0.001672229279488645}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:02:18,162] Trial 42 finished with value: 0.982936926373964 and parameters: {'loss': 'huber', 'learning_rate': 0.0352543733271902, 'n_estimators': 267, 'criterion': 'squared_error', 'min_samples_split': 6, 'min_samples_leaf': 15, 'max_depth': 5, 'min_impurity_decrease': 0.09627371582409237, 'ccp_alpha': 0.001097657712223677}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:02:36,242] Trial 43 finished with value: 0.983431047440815 and parameters: {'loss': 'huber', 'learning_rate': 0.08753456634255496, 'n_estimators': 377, 'criterion': 'squared_error', 'min_samples_split': 8, 'min_samples_leaf': 15, 'max_depth': 7, 'min_impurity_decrease': 0.06880478585150908, 'ccp_alpha': 0.0013591417991536583}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:02:39,856] Trial 44 finished with value: -2.0949187615476723 and parameters: {'loss': 'quantile', 'learning_rate': 0.05558217296824398, 'n_estimators': 467, 'criterion': 'squared_error', 'min_samples_split': 12, 'min_samples_leaf': 13, 'max_depth': 6, 'min_impurity_decrease': 0.08003008185532953, 'ccp_alpha': 0.00205455699175369}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:02:54,032] Trial 45 finished with value: 0.9831669702278228 and parameters: {'loss': 'huber', 'learning_rate': 0.029402463953909275, 'n_estimators': 401, 'criterion': 'friedman_mse', 'min_samples_split': 9, 'min_samples_leaf': 17, 'max_depth': 5, 'min_impurity_decrease': 0.091361058852822, 'ccp_alpha': 5.503902751108304e-05}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:02:58,106] Trial 46 finished with value: 0.722643797453858 and parameters: {'loss': 'absolute_error', 'learning_rate': 0.10070654517114594, 'n_estimators': 429, 'criterion': 'squared_error', 'min_samples_split': 6, 'min_samples_leaf': 18, 'max_depth': 10, 'min_impurity_decrease': 0.08667374026038203, 'ccp_alpha': 0.0008430020810617413}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:03:07,448] Trial 47 finished with value: 0.9831923431990044 and parameters: {'loss': 'huber', 'learning_rate': 0.1439546460729249, 'n_estimators': 315, 'criterion': 'squared_error', 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_depth': 4, 'min_impurity_decrease': 0.09944429849452922, 'ccp_alpha': 0.0038446450490263653}. Best is trial 41 with value: 0.9836454007488242.
[I 2026-04-11 11:03:28,161] Trial 48 finished with value: 0.9836882729439541 and parameters: {'loss': 'huber', 'learning_rate': 0.049257176968997535, 'n_estimators': 499, 'criterion': 'friedman_mse', 'min_samples_split': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'min_impurity_decrease': 0.06272164915822126, 'ccp_alpha': 0.00492786541927825}. Best is trial 48 with value: 0.9836882729439541.
[I 2026-04-11 11:03:54,497] Trial 49 finished with value: 0.9825830169206451 and parameters: {'loss': 'huber', 'learning_rate': 0.17460906842744217, 'n_estimators': 493, 'criterion': 'friedman_mse', 'min_samples_split': 6, 'min_samples_leaf': 20, 'max_depth': 8, 'min_impurity_decrease': 0.06200606806883894, 'ccp_alpha': 0.004966195203438298}. Best is trial 48 with value: 0.9836882729439541.

In [35]:
print(f"Best params: {study.best_params}")
print(f"Best R^2: {study.best_value}")

metrics(GradientBoostingRegressor(**study.best_params), 'GradientBoostingRegressor', study.best_value)

Best params: {'loss': 'huber', 'learning_rate': 0.049257176968997535, 'n_estimators': 499, 'criterion': 'friedman_mse', 'min_samples_split': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'min_impurity_decrease': 0.06272164915822126, 'ccp_alpha': 0.00492786541927825}
Best R^2: 0.9836882729439541

In [36]:
results_df = pd.DataFrame(results)
results_df

                       Model       MAE      RMSE    MAPE  R2 (Test)  R2 (CV)
0           BaggingRegressor  282.8983  525.0476  0.0820    0.97838  0.98062
1  GradientBoostingRegressor  236.5839  454.5862  0.0708    0.98379  0.98369

### StackingRegressor

In [41]:
def objective(trial):
    dt_max_depth = trial.suggest_int('dt_max_depth', 3, 5)
    dt_min_samples = trial.suggest_int('dt_min_samples_split', 2, 20)
    
    knn_neighbors = trial.suggest_int('knn_neighbors', 3, 25)
    knn_weights = trial.suggest_categorical('knn_weights', ['uniform', 'distance'])

    en_alpha = trial.suggest_float('en_alpha', 0.001, 1.0, )
    en_l1 = trial.suggest_float('en_l1_ratio', 0, 1)

    estimators = [
        ('dt', DecisionTreeRegressor(max_depth=dt_max_depth, 
                                     min_samples_split=dt_min_samples, 
                                     random_state=81)),
        ('knn', KNeighborsRegressor(n_neighbors=knn_neighbors, 
                                    weights=knn_weights))
    ]
    
    final_mod = ElasticNet(alpha=en_alpha, l1_ratio=en_l1, random_state=81)

    model = StackingRegressor(
        estimators=estimators,
        final_estimator=final_mod,
        cv=5, 
        n_jobs=-1
    )

    kf = KFold(n_splits=5, shuffle=True, random_state=81)

    score = cross_val_score(
        model, 
        x_regression, 
        y_regression, 
        scoring='r2', 
        cv=kf, 
        n_jobs=-1
    ).mean()

    return score

In [46]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-04-11 14:39:13,739] A new study created in memory with name: no-name-2e0bf05f-313b-4249-89da-1306bf831479
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
[I 2026-04-11 14:39:14,748] Trial 0 finished with value: 0.9156797011798152 and parameters: {'dt_max_depth': 4, 'dt_min_samples_split': 7, 'knn_neighbors': 15, 'knn_weights': 'uniform', 'en_alpha': 0.5650671306455202, 'en_l1_ratio': 0.13682473052152555}. Best is trial 0 with value: 0.9156797011798152.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
[I 2026-04-11 14:39:15,544] Trial 1 finished with value: 0.9296977198992262 and parameters: {'dt_max_depth': 5, 'dt_min_samples_split': 7, 'knn_neighbors': 8, 'knn_weights': 'distance', 'en_alpha': 0.17218925392450057, 'en_l1_ratio': 0.9845246100720577}. Best is trial 1 with value: 0.9296977198992262.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
[I 2026-04-11 14:39:16,373] Trial 2 finished with value: 0.9294689034842241 and parameters: {'dt_max_depth': 5, 'dt_min_samples_split': 20, 'knn_neighbors': 9, 'knn_weights': 'distance', 'en_alpha': 0.0837423174266417, 'en_l1_ratio': 0.24551426961976486}. Best is trial 1 with value: 0.9296977198992262.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
[I 2026-04-11 14:39:17,084] Trial 3 finished with value: 0.9182914758539391 and parameters: {'dt_max_depth': 4, 'dt_min_samples_split': 15, 'knn_neighbors': 7, 'knn_weights': 'uniform', 'en_alpha': 0.8975437227386152, 'en_l1_ratio': 0.31906698518139187}. Best is trial 1 with value: 0.9296977198992262.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
[I 2026-04-11 14:39:18,049] Trial 4 finished with value: 0.9162011026398298 and parameters: {'dt_max_depth': 3, 'dt_min_samples_split': 14, 'knn_neighbors': 16, 'knn_weights': 'distance', 'en_alpha': 0.5459503895870405, 'en_l1_ratio': 0.4070081122223945}. Best is trial 1 with value: 0.9296977198992262.
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [48]:
bp = study.best_params

base_models = [
    ('dt', DecisionTreeRegressor(
        max_depth=bp['dt_max_depth'], 
        min_samples_split=bp['dt_min_samples_split'], 
        random_state=81
    )),
    ('knn', KNeighborsRegressor(
        n_neighbors=bp['knn_neighbors'], 
        weights=bp['knn_weights']
    ))
]

final_res = ElasticNet(
    alpha=bp['en_alpha'], 
    l1_ratio=bp['en_l1_ratio'], 
    random_state=81
)

best_stacking_model = StackingRegressor(
    estimators=base_models,
    final_estimator=final_res,
    cv=5,
    n_jobs=-1
)

metrics(best_stacking_model, 'StackingRegressor', study.best_value)

/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/irinaaristova/Documents/Programming/ml-learning/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [49]:
results_df = pd.DataFrame(results)
results_df

                       Model       MAE      RMSE    MAPE  R2 (Test)  R2 (CV)
0           BaggingRegressor  282.8983  525.0476  0.0820    0.97838  0.98062
1  GradientBoostingRegressor  236.5839  454.5862  0.0708    0.98379  0.98369
2          StackingRegressor  459.8931  774.0993  0.1447    0.95300  0.93145

#### Вывод

- Наилучшую точность показал алгоритм `GradientBoostingRegressor`, достигнув самого высокого $R^2 = 0.984$ и потребовав меньше всего времени.
- `GradientBoostingRegressor` продемонстрировал высокую стабильность и сопоставимый результат $R^2 = 0.981$ на кросс-валидации, однако занял больше всего времени.
- `StackingRegressor` в данной конфигурации показал наименее эффективный результат с $R^2$ = 0.93. Это может быть связано с недостаточной сложностью базовых моделей или необходимостью более тонкой настройки мета-регрессора для эффективного комбинирования различных алгоритмов.

### Задача классификации

In [14]:
classification = pd.read_csv("../data/credit_card_fraud_filtered.csv")

In [15]:
y_classification = classification['fraud']
x_classification = classification.drop('fraud', axis=1)